version: '3'
services:
  np-exploration:
    image: pgnp:latest
    container_name: exploration
    ports:
      - "42666:42666"
    environment:
      - PGPORT=4266
      - POSTGRES_DB=noisepage
      - POSTGRES_USER=noisepage
      - POSTGRES_PASSWORD=terrier
      - NP_REPLICATION_TYPE=exploratory
      - COMPOSE_PROJECT_NAME=exploration
    volumes:
      - pgdata-replica:/replica-pgdata
      - pgdata-exploration:/pgdata
volumes:
  pgdata-replica:
    external: true
  pgdata-exploration:
    external: true
